from enum import Enum


class UserRole(str, Enum):
    OWNER = "OWNER"
    MANAGER = "MANAGER"
    STAFF = "STAFF"


class PricingType(str, Enum):
    MRP = "MRP"
    OWN_PRICE = "OWN_PRICE"


class PurchaseStatus(str, Enum):
    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"


class StockMovementType(str, Enum):
    PURCHASE = "PURCHASE"
    SALE = "SALE"
    CUSTOMER_RETURN = "CUSTOMER_RETURN"
    SUPPLIER_RETURN = "SUPPLIER_RETURN"
    DAMAGE = "DAMAGE"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
    SALE_EDIT_RETURN = "SALE_EDIT_RETURN"
    SALE_EDIT_DECREASE = "SALE_EDIT_DECREASE"
    SALE_VOID = "SALE_VOID"


class SaleStatus(str, Enum):
    COMPLETED = "COMPLETED"
    EDITED = "EDITED"
    PARTIALLY_RETURNED = "PARTIALLY_RETURNED"
    RETURNED = "RETURNED"
    VOIDED = "VOIDED"


class DocumentJobStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PREPROCESSING = "PREPROCESSING"
    OCR_RUNNING = "OCR_RUNNING"
    AI_EXTRACTION = "AI_EXTRACTION"
    PRODUCT_MATCHING = "PRODUCT_MATCHING"
    VALIDATING = "VALIDATING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class UploadFileType(str, Enum):
    INVOICE_IMAGE = "INVOICE_IMAGE"
    INVOICE_PDF = "INVOICE_PDF"
    PRODUCT_IMAGE = "PRODUCT_IMAGE"
