from enum import Enum


class UserRole(str, Enum):
    OWNER = "OWNER"
    MANAGER = "MANAGER"
    STAFF = "STAFF"


class PricingType(str, Enum):
    MRP = "MRP"
    OWN_PRICE = "OWN_PRICE"


class PurchaseStatus(str, Enum):
    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    VOIDED = "VOIDED"


class StockMovementType(str, Enum):
    PURCHASE = "PURCHASE"
    SALE = "SALE"
    CUSTOMER_RETURN = "CUSTOMER_RETURN"
    SUPPLIER_RETURN = "SUPPLIER_RETURN"
    DAMAGE = "DAMAGE"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
    SALE_EDIT_RETURN = "SALE_EDIT_RETURN"
    SALE_EDIT_DECREASE = "SALE_EDIT_DECREASE"
    SALE_VOID = "SALE_VOID"
    PURCHASE_VOID = "PURCHASE_VOID"
    OPENING_STOCK = "OPENING_STOCK"
    STOCK_RESET_OUT = "STOCK_RESET_OUT"
    STOCK_COUNT_IN = "STOCK_COUNT_IN"
    STOCK_COUNT_OUT = "STOCK_COUNT_OUT"


class StockScanMode(str, Enum):
    PURCHASE_RECEIVING = "PURCHASE_RECEIVING"
    OPENING_STOCK = "OPENING_STOCK"
    PHYSICAL_COUNT = "PHYSICAL_COUNT"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
    STOCK_TRANSFER = "STOCK_TRANSFER"


class StockScanStatus(str, Enum):
    DRAFT = "DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"


class StockScanQuantityMode(str, Enum):
    INCREMENT = "INCREMENT"
    QUANTITY_ENTRY = "QUANTITY_ENTRY"


class SaleStatus(str, Enum):
    DRAFT = "DRAFT"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    EDITED = "EDITED"
    PARTIALLY_RETURNED = "PARTIALLY_RETURNED"
    RETURNED = "RETURNED"
    VOIDED = "VOIDED"


class DocumentJobStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PREPROCESSING = "PREPROCESSING"
    OCR_RUNNING = "OCR_RUNNING"
    AI_EXTRACTION = "AI_EXTRACTION"
    PRODUCT_MATCHING = "PRODUCT_MATCHING"
    VALIDATING = "VALIDATING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class UploadFileType(str, Enum):
    INVOICE_IMAGE = "INVOICE_IMAGE"
    INVOICE_PDF = "INVOICE_PDF"
    PRODUCT_IMAGE = "PRODUCT_IMAGE"


class OpeningStockImportStatus(str, Enum):
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY_TO_CONFIRM = "READY_TO_CONFIRM"
    POSTING = "POSTING"
    COMPLETED = "COMPLETED"
    REVERSED = "REVERSED"
    FAILED = "FAILED"
