import { FormEvent, useMemo, useState } from "react";
import { Search } from "lucide-react";
import { api } from "../api/client";
import type { Product } from "../types";
import Dialog from "./Dialog";
import { useToast } from "./ToastProvider";
import { Button } from "./ui/button";

type Assignment = { barcode_id: string; product_id: string; variant_id: string; product_name: string; brand_name?: string | null; category_name?: string | null; size?: string | null; color?: string | null; current_stock: number; active: boolean };
type Lookup = { barcode: string; status: "AVAILABLE" | "UNIQUE" | "MULTIPLE" | "STALE"; message: string; assignments: Assignment[] };
type DeletionCheck = { barcode: string; active_assignments: number; historical_references: number; draft_references: number; audit_references: number; can_permanently_delete: boolean; reason?: string | null };

export default function BarcodeLookupDialog({ open, products, onClose, onManageVariant, onChanged }: { open: boolean; products: Product[]; onClose: () => void; onManageVariant: (variantId: string) => void; onChanged: () => void }) {
  const toast = useToast();
  const [barcode, setBarcode] = useState(""); const [lookup, setLookup] = useState<Lookup | null>(null); const [check, setCheck] = useState<DeletionCheck | null>(null); const [targetId, setTargetId] = useState(""); const [sourceId, setSourceId] = useState(""); const [pending, setPending] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false);
  const variants = useMemo(() => products.flatMap((product) => product.variants.filter((variant) => variant.is_active).map((variant) => ({ id: variant.id, label: `${product.name} · ${variant.size || "Standard"}${variant.color ? ` · ${variant.color}` : ""}` }))), [products]);
  async function refresh(value = barcode) { const normalised = value.trim(); if (!normalised) return; const [nextLookup, nextCheck] = await Promise.all([api.get<Lookup>(`/barcodes/lookup/${encodeURIComponent(normalised)}`), api.get<DeletionCheck>(`/barcodes/lookup/${encodeURIComponent(normalised)}/deletion-check`)]); setLookup(nextLookup); setCheck(nextCheck); setConfirmDelete(false); }
  async function find(event?: FormEvent) { event?.preventDefault(); if (!barcode.trim()) return; setPending(true); try { await refresh(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to find barcode"); } finally { setPending(false); } }
  async function transfer() { const lookupBarcode = lookup?.barcode; const source = lookup?.assignments.find((assignment) => assignment.variant_id === sourceId) ?? lookup?.assignments[0]; if (!source || !targetId || !lookupBarcode) return; setPending(true); try { await api.post(`/barcodes/${source.barcode_id}/transfer`, { source_variant_id: source.variant_id, target_variant_id: targetId, confirm_transfer: true }); toast.success("Barcode mapping transferred. Stock quantities are unchanged."); await refresh(lookupBarcode); onChanged(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to transfer barcode"); } finally { setPending(false); } }
  async function remove(assignment?: Assignment) { const first = assignment ?? lookup?.assignments[0]; if (!first || !window.confirm(assignment ? `Remove barcode ${lookup?.barcode} from ${assignment.product_name} / ${assignment.size || "Standard"}?` : `Remove barcode ${lookup?.barcode} from all variants?`)) return; setPending(true); try { if (assignment) await api.delete(`/barcodes/${first.barcode_id}/targets/${assignment.variant_id}`); else await api.delete(`/barcodes/${first.barcode_id}`); toast.success("Current barcode assignment removed. Historical transaction records were preserved."); await refresh(lookup?.barcode); onChanged(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to remove barcode"); } finally { setPending(false); } }
  async function permanentlyDelete() { if (!lookup || !confirmDelete) return; setPending(true); try { await api.post(`/barcodes/lookup/${encodeURIComponent(lookup.barcode)}/permanent-delete`, { confirmation: "DELETE BARCODE" }); toast.success("Barcode registration permanently deleted"); await refresh(lookup.barcode); onChanged(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to permanently delete barcode"); } finally { setPending(false); } }
  const label = lookup?.status === "UNIQUE" ? "Assigned" : lookup?.status === "MULTIPLE" ? "Multiple" : lookup?.status === "STALE" ? "Stale" : "Available";
  return <Dialog open={open} onClose={onClose} title="Find Barcode" description="Review current ownership and historical dependencies before changing a barcode." maxWidth="lg">
    <form className="flex gap-2" onSubmit={(event) => void find(event)}><input autoFocus className="field-input font-mono" placeholder="Scan or enter barcode" value={barcode} onChange={(event) => setBarcode(event.target.value)} /><Button type="submit" disabled={pending}><Search size={16} /> Find</Button></form>
    {lookup ? <div className="mt-5 space-y-4"><section className={`rounded-lg border p-3 ${lookup.status === "AVAILABLE" ? "border-emerald-200 bg-emerald-50" : lookup.status === "STALE" ? "border-amber-200 bg-amber-50" : "border-teal-200 bg-teal-50"}`}><div className="text-xs font-semibold uppercase tracking-wide">Barcode</div><div className="font-mono text-sm">{lookup.barcode}</div><strong className="mt-2 block">Status: {label}</strong><p className="mt-1 text-sm">{lookup.status === "AVAILABLE" ? "This barcode is not currently assigned to any product." : lookup.message}</p>{check ? <div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><span>Active assignments: <strong>{check.active_assignments}</strong></span><span>Historical references: <strong>{check.historical_references}</strong></span></div> : null}</section>
      {lookup.assignments.map((assignment) => <section key={assignment.variant_id} className="rounded-lg border border-line p-3 text-sm"><strong>{assignment.product_name}</strong><div>{assignment.brand_name || "Unbranded"} · {assignment.category_name || "Uncategorised"}</div><div>{assignment.size || "Standard"}{assignment.color ? ` · ${assignment.color}` : ""} · Stock {assignment.current_stock} · {assignment.active ? "Active" : "Inactive"}</div><div className="mt-3 flex flex-wrap gap-2"><Button type="button" size="sm" variant="secondary" onClick={() => onManageVariant(assignment.variant_id)}>Change</Button><Button type="button" size="sm" variant="secondary" className="text-rose-700" disabled={pending} onClick={() => void remove(assignment)}>Remove Assignment</Button></div></section>)}
      {lookup.assignments.length ? <section className="rounded-lg border border-line p-3"><label className="field-label">Mapping to transfer<select className="field-input mt-1" value={sourceId} onChange={(event) => setSourceId(event.target.value)}><option value="">Select current mapping</option>{lookup.assignments.map((assignment) => <option key={assignment.variant_id} value={assignment.variant_id}>{assignment.product_name} · {assignment.size || "Standard"}{assignment.color ? ` · ${assignment.color}` : ""}</option>)}</select></label><label className="mt-3 block field-label">Transfer to exact variant<select className="field-input mt-1" value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">Select variant</option>{variants.map((variant) => <option key={variant.id} value={variant.id}>{variant.label}</option>)}</select></label><div className="mt-3 flex flex-wrap gap-2"><Button type="button" disabled={pending || !targetId || !sourceId} onClick={() => void transfer()}>Transfer Mapping</Button>{lookup.assignments.length > 1 ? <Button type="button" variant="destructive" disabled={pending} onClick={() => void remove()}>Remove Barcode From All Items</Button> : null}</div></section> : null}
      {lookup.status === "AVAILABLE" ? <section className="rounded-lg border border-line p-3 text-sm"><strong>{check?.historical_references ? "Available with history" : "Available with no history"}</strong><p className="mt-1 text-muted">{check?.reason || "Assign it to the correct product and variant when ready."}</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={onClose}>Assign</Button>{check?.can_permanently_delete ? <Button type="button" variant="destructive" disabled={pending} onClick={() => setConfirmDelete(true)}>Delete Barcode Permanently</Button> : null}</div></section> : null}
      {confirmDelete ? <section className="rounded-lg border border-rose-300 bg-rose-50 p-3 text-sm text-rose-950"><strong>Safe to permanently delete</strong><p className="mt-1">Permanently delete barcode {lookup.barcode} from the database? This cannot be undone.</p><div className="mt-3 flex gap-2"><Button type="button" variant="destructive" disabled={pending} onClick={() => void permanentlyDelete()}>Delete Permanently</Button><Button type="button" variant="secondary" onClick={() => setConfirmDelete(false)}>Cancel</Button></div></section> : null}
    </div> : null}
  </Dialog>;
}
