import { FormEvent, useMemo, useState } from "react";
import { Search } from "lucide-react";
import { api } from "../api/client";
import type { Product } from "../types";
import Dialog from "./Dialog";
import { useToast } from "./ToastProvider";
import { Button } from "./ui/button";

type Assignment = { barcode_id: string; product_id: string; variant_id: string; product_name: string; brand_name?: string | null; category_name?: string | null; size?: string | null; color?: string | null; current_stock: number; active: boolean };
type Lookup = { barcode: string; status: "AVAILABLE" | "UNIQUE" | "SHARED" | "CONFLICT" | "STALE"; message: string; assignments: Assignment[] };

export default function BarcodeLookupDialog({ open, products, onClose, onManageVariant, onChanged }: { open: boolean; products: Product[]; onClose: () => void; onManageVariant: (variantId: string) => void; onChanged: () => void }) {
  const toast = useToast();
  const [barcode, setBarcode] = useState(""); const [lookup, setLookup] = useState<Lookup | null>(null); const [targetId, setTargetId] = useState(""); const [pending, setPending] = useState(false);
  const variants = useMemo(() => products.flatMap((product) => product.variants.filter((variant) => variant.is_active).map((variant) => ({ id: variant.id, label: `${product.name} · ${variant.size || "Standard"}${variant.color ? ` · ${variant.color}` : ""}` }))), [products]);
  async function find(event?: FormEvent) { event?.preventDefault(); if (!barcode.trim()) return; setPending(true); try { setLookup(await api.get<Lookup>(`/barcodes/lookup/${encodeURIComponent(barcode.trim())}`)); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to find barcode"); } finally { setPending(false); } }
  async function transfer() { if (!lookup?.assignments[0] || !targetId) return; setPending(true); try { await api.post(`/barcodes/${lookup.assignments[0].barcode_id}/transfer`, { target_variant_id: targetId, confirm_transfer: true }); toast.success("Barcode transferred"); await find(); onChanged(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to transfer barcode"); } finally { setPending(false); } }
  async function remove(assignment?: Assignment) { const first = assignment ?? lookup?.assignments[0]; if (!first || !window.confirm(assignment ? `Remove barcode ${lookup?.barcode} from ${assignment.product_name} / ${assignment.size || "Standard"}?` : `Remove barcode ${lookup?.barcode} from all variants?`)) return; setPending(true); try { if (assignment) await api.delete(`/barcodes/${first.barcode_id}/targets/${assignment.variant_id}`); else await api.delete(`/barcodes/${first.barcode_id}`); toast.success("Barcode assignment removed"); await find(); onChanged(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to remove barcode"); } finally { setPending(false); } }
  return <Dialog open={open} onClose={onClose} title="Find Barcode" description="Check the current barcode assignment before changing, transferring, or removing it." maxWidth="lg"><form className="flex gap-2" onSubmit={(event) => void find(event)}><input autoFocus className="field-input font-mono" placeholder="Scan or enter barcode" value={barcode} onChange={(event) => setBarcode(event.target.value)} /><Button type="submit" disabled={pending}><Search size={16} /> Find</Button></form>{lookup ? <div className="mt-5 space-y-4"><section className={`rounded-lg border p-3 ${lookup.status === "AVAILABLE" ? "border-emerald-200 bg-emerald-50" : lookup.status === "STALE" || lookup.status === "CONFLICT" ? "border-amber-200 bg-amber-50" : "border-teal-200 bg-teal-50"}`}><div className="font-mono text-sm">{lookup.barcode}</div><strong className="mt-1 block">{lookup.status === "AVAILABLE" ? "Barcode Available" : lookup.message}</strong></section>{lookup.assignments.map((assignment) => <section key={assignment.variant_id} className="rounded-lg border border-line p-3 text-sm"><strong>{assignment.product_name}</strong><div>{assignment.brand_name || "Unbranded"} · {assignment.category_name || "Uncategorised"}</div><div>{assignment.size || "Standard"}{assignment.color ? ` · ${assignment.color}` : ""} · Stock {assignment.current_stock} · {assignment.active ? "Active" : "Inactive"}</div><div className="mt-3 flex flex-wrap gap-2"><Button type="button" size="sm" variant="secondary" onClick={() => onManageVariant(assignment.variant_id)}>Change</Button><Button type="button" size="sm" variant="secondary" className="text-rose-700" disabled={pending} onClick={() => void remove(assignment)}>Remove</Button></div></section>)}{lookup.assignments.length ? <section className="rounded-lg border border-line p-3"><label className="field-label">Transfer to exact variant<select className="field-input mt-1" value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">Select variant</option>{variants.map((variant) => <option key={variant.id} value={variant.id}>{variant.label}</option>)}</select></label><div className="mt-3 flex flex-wrap gap-2"><Button type="button" disabled={pending || !targetId} onClick={() => void transfer()}>Transfer</Button>{lookup.assignments.length > 1 ? <Button type="button" variant="destructive" disabled={pending} onClick={() => void remove()}>Remove from all variants</Button> : null}</div></section> : null}</div> : null}</Dialog>;
}
