import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "../api/client";
import { Button } from "./ui/button";
import ErrorState from "./ErrorState";
type Choice = { id: string; name: string };
type Row = { product: string; category: string; brand: string; size?: string; color?: string; sku: string; current_stock: number; minimum_stock: number };
export default function LowStockReport() {
  const [category, setCategory] = useState(""); const [brand, setBrand] = useState(""); const [supplier, setSupplier] = useState(""); const [page, setPage] = useState(1);
  const categories = useQuery({ queryKey: ["low-stock-categories"], queryFn: () => api.get<Choice[]>("/categories?limit=100") });
  const brands = useQuery({ queryKey: ["low-stock-brands"], queryFn: () => api.get<Choice[]>("/brands?limit=100") });
  const suppliers = useQuery({ queryKey: ["low-stock-suppliers"], queryFn: () => api.get<Choice[]>("/suppliers?limit=100") });
  const query = useQuery({ queryKey: ["low-stock", category, brand, supplier, page], queryFn: () => api.get<{ items: Row[]; has_more: boolean }>(`/reports/low-stock?page=${page}${category ? `&category_id=${category}` : ""}${brand ? `&brand_id=${brand}` : ""}${supplier ? `&supplier_id=${supplier}` : ""}`) });
  return <details className="ds-surface p-4"><summary className="cursor-pointer py-2 text-lg font-bold">Low stock by size</summary><p className="my-3 text-sm">Set a size's minimum in Products → Manage variant. An empty size minimum uses the product's setting. Supplier filters use confirmed receipts.</p><div className="grid gap-3 sm:grid-cols-3">{[{ label: "Category", value: category, set: setCategory, choices: categories.data }, { label: "Brand", value: brand, set: setBrand, choices: brands.data }, { label: "Supplier", value: supplier, set: setSupplier, choices: suppliers.data }].map((filter) => <label key={filter.label} className="field-label">{filter.label}<select className="field-input" value={filter.value} onChange={(event) => { filter.set(event.target.value); setPage(1); }}><option value="">All</option>{filter.choices?.map((choice) => <option key={choice.id} value={choice.id}>{choice.name}</option>)}</select></label>)}</div>{query.error ? <ErrorState message={query.error.message} /> : <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Product / size", "Brand", "Stock", "Minimum"].map((title) => <th key={title} className="p-2">{title}</th>)}</tr></thead><tbody>{query.data?.items.map((row) => <tr key={row.sku} className="border-t"><td className="p-2"><strong>{row.product}</strong><br />{[row.size,row.color].filter(Boolean).join(" · ")}<small className="block">{row.sku}</small></td><td className="p-2">{row.brand}</td><td className="p-2 font-bold">{row.current_stock === 0 ? "Out of stock" : row.current_stock}</td><td className="p-2">{row.minimum_stock}</td></tr>)}</tbody></table>{query.data?.items.length === 0 && <p className="p-3">No items below the selected minimums.</p>}</div>}<div className="mt-3 flex items-center justify-between"><Button variant="secondary" disabled={page===1} onClick={() => setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="secondary" disabled={!query.data?.has_more} onClick={() => setPage(page+1)}>Next</Button></div></details>;
}
