import { useRef, useState } from "react";
import type { Sale } from "../types";
import { useStoreSettings } from "../hooks/useStoreSettings";
import { printDocument } from "../utils/printing";
import { money } from "../utils/format";
import { Button } from "./ui/button";
import ErrorState from "./ErrorState";

export default function ThermalReceipt({ sale }: { sale: Sale }) {
  const settings = useStoreSettings(); const ref = useRef<HTMLDivElement>(null); const [error, setError] = useState("");
  const store = settings.data; const receipt = store?.receipt;
  function print() { if (!ref.current || !receipt) return; try { printDocument(ref.current.innerHTML, receipt.width_mm, receipt.margin_mm, receipt.copies); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Printing failed."); } }
  const savings = Math.max(0, sale.items.reduce((total, item) => total + Math.max(Number(item.mrp_snapshot || 0), Number(item.unit_price)) * item.quantity, 0) - Number(sale.grand_total ?? sale.total_amount));
  const sum = (field: "taxable_value" | "cgst_amount" | "sgst_amount" | "igst_amount") => sale.items.reduce((total, item) => total + Number(item[field] || 0), 0);
  return <div className="mt-5 space-y-4 text-left">{settings.error ? <ErrorState message="Receipt settings could not be loaded. Reconnect and reopen the invoice to print." /> : null}<div ref={ref} id="printable-invoice" className="mx-auto border bg-white p-3 text-black" style={{ width: `${receipt?.width_mm ?? 80}mm`, maxWidth: "100%", fontSize: "10pt" }}>
    <div className="receipt-title" style={{ textAlign: "center" }}>{store?.logo_url ? <img src={store.logo_url} alt="" style={{ maxWidth: "40mm", maxHeight: "20mm", margin: "auto" }} /> : null}<h2><strong>{store?.name ?? "Rainbow Fashions"}</strong></h2>{store?.address && <p>{store.address}</p>}{store?.phone && <p>{store.phone}</p>}{receipt?.show_gst && store?.gstin && <p>GSTIN: {store.gstin}</p>}</div><hr /><p>Bill: {sale.invoice_number}</p><p>{new Date(sale.sale_date).toLocaleString("en-IN", { timeZone: store?.timezone ?? "Asia/Kolkata" })}</p><p>Cashier: {sale.cashier?.full_name ?? "—"}</p><p>Customer: {sale.customer_name || "Walk-in"}</p>{sale.status === "VOIDED" && <p><strong>VOIDED</strong></p>}<hr />
    <table style={{ width: "100%" }}><thead><tr><th>Item / Qty × Price</th><th style={{ textAlign: "right" }}>Amount</th></tr></thead><tbody>{sale.items.map((item) => <tr className="receipt-line" key={item.id}><td><strong>{item.product_name}</strong><br /><small>{[item.brand_snapshot, item.size_snapshot, item.color_snapshot, item.style_snapshot].filter(Boolean).join(" · ")}</small><br /><small>{item.mrp_snapshot && Number(item.mrp_snapshot) !== Number(item.unit_price) ? `MRP ${money(item.mrp_snapshot)} · ` : ""}{item.quantity} × {money(item.unit_price)}{Number(item.discount_amount) > 0 ? ` · Less ${money(item.discount_amount!)}` : ""}</small>{receipt?.show_gst && item.hsn_snapshot ? <><br /><small>HSN {item.hsn_snapshot} · GST {item.gst_rate_snapshot}%</small></> : null}</td><td style={{ textAlign: "right", verticalAlign: "top" }}>{money(item.line_total)}</td></tr>)}</tbody></table><hr /><table><tbody><tr><td>Subtotal</td><td>{money(sale.subtotal)}</td></tr><tr><td>Bill discount</td><td>− {money(sale.discount_amount ?? sale.discount)}</td></tr>{receipt?.show_gst && sum("taxable_value") > 0 ? <><tr><td>Taxable value</td><td>{money(sum("taxable_value"))}</td></tr>{(["cgst_amount", "sgst_amount", "igst_amount"] as const).map((field) => sum(field) > 0 ? <tr key={field}><td>{field.split("_")[0].toUpperCase()} (included)</td><td>{money(sum(field))}</td></tr> : null)}</> : null}<tr className="receipt-total"><td>Total</td><td>{money(sale.grand_total ?? sale.total_amount)}</td></tr></tbody></table>{savings > 0 && <p>You saved {money(savings)}</p>}<p>Payment: {sale.payment_mode}</p>{sale.payment_reference && <p>Reference: {sale.payment_reference}</p>}<hr /><p>{receipt?.return_policy}</p><p style={{ textAlign: "center" }}>{receipt?.thank_you ?? "Thank you for shopping with us!"}</p>
  </div>{error && <ErrorState message={error} />}<Button type="button" disabled={!receipt} onClick={print}>Print / Reprint Bill</Button></div>;
}
