-- Development-only seed placeholder.
--
-- Production and normal Docker startup intentionally load schema.sql only.
-- Do not add users, passwords, authentication records, or sample business data
-- here. Use backend/scripts/bootstrap_owner.py to create the first owner.
--
-- Development catalog fixtures, when needed, belong in an explicitly invoked
-- test or development-only script and must never be mounted by production Compose.
