import { useEffect, useState } from "react";
import { BarChart3, Boxes, ClipboardPenLine, FileUp, FolderTree, LayoutDashboard, LogOut, Menu, Package, PackagePlus, ReceiptIndianRupee, ReceiptText, ScanLine, Settings, ShieldCheck, ShoppingCart, Truck, UsersRound, X, RotateCcw, Printer, ListChecks, DatabaseBackup } from "lucide-react";
import { NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../hooks/useAuth";
import { routeAllowed } from "../routes/permissions";
import ConnectionStatus from "../components/ConnectionStatus";

const groups = [
  { label: "", links: [{ to: "/", label: "Dashboard", icon: LayoutDashboard }] },
  { label: "Billing", links: [{ to: "/sales", label: "New Sale", icon: ShoppingCart }, { to: "/sales/history", label: "Sales History", icon: ReceiptText }, { to: "/sales/returns", label: "Returns / Exchanges", icon: RotateCcw }, { to: "/day-closing", label: "Day Closing", icon: ListChecks }] },
  { label: "Inventory", links: [{ to: "/stock", label: "Stock", icon: Boxes }, { to: "/stock/scan", label: "Scan & Add Stock", icon: ScanLine }, { to: "/stock/quick", label: "Quick Stock Entry", icon: PackagePlus }, { to: "/stock/opening-import", label: "Opening Stock Import", icon: FileUp }, { to: "/stock/adjustment", label: "Stock Adjustment", icon: ClipboardPenLine }, { to: "/stock/integrity", label: "Inventory Integrity", icon: ShieldCheck }] },
  { label: "Products", links: [{ to: "/products", label: "Products & Barcode Labels", icon: Package }, { to: "/categories-brands", label: "Categories & Brands", icon: FolderTree }] },
  { label: "Purchases", links: [{ to: "/purchases", label: "Purchases", icon: PackagePlus }, { to: "/purchases/quick", label: "Quick Purchase", icon: PackagePlus }, { to: "/purchases/returns", label: "Purchase Returns", icon: RotateCcw }, { to: "/suppliers", label: "Suppliers", icon: Truck }] },
  { label: "Business", links: [{ to: "/customers", label: "Customers", icon: UsersRound }, { to: "/expenses", label: "Expenses", icon: ReceiptIndianRupee }, { to: "/reports", label: "Reports", icon: BarChart3 }] },
  { label: "Administration", links: [{ to: "/users", label: "Users & Roles", icon: UsersRound }, { to: "/settings/security", label: "Security", icon: ShieldCheck }, { to: "/backup-status", label: "Backup Status", icon: DatabaseBackup }, { to: "/audit-log", label: "Audit Log", icon: ListChecks }, { to: "/store-settings", label: "Store Settings", icon: Settings }, { to: "/printer-settings", label: "Printer Settings", icon: Printer }] },
];

function SidebarContent({ onNavigate }: { onNavigate?: () => void }) {
  const { user } = useAuth();
  return <div className="flex h-full flex-col bg-primary-800 text-white"><div className="border-b border-white/15 px-5 py-6"><div className="text-2xl font-bold">Rainbow Fashions</div><div className="mt-1 text-sm text-primary-100">Inventory & Billing</div></div><nav className="flex-1 space-y-4 overflow-y-auto px-3 py-4" aria-label="Main navigation">{groups.map((group) => { const links = group.links.filter((link) => user && routeAllowed(link.to, user.role)); if (!links.length) return null; return <section key={group.label}>{group.label ? <h2 className="mb-1 px-3 text-sm font-bold text-primary-100">{group.label}</h2> : null}{links.map((link) => { const Icon = link.icon; return <NavLink key={link.to} to={link.to} end onClick={onNavigate} className={({ isActive }) => `focus-ring flex min-h-12 items-center gap-3 rounded-lg px-3 py-2 text-base font-medium ${isActive ? "bg-white text-primary-900" : "text-white hover:bg-white/15"}`}><Icon size={21} aria-hidden="true" /><span>{link.label}</span></NavLink>; })}</section>; })}</nav></div>;
}

export default function AppLayout() {
  const { user, logout } = useAuth(); const location = useLocation(); const navigate = useNavigate();
  const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { if (!mobileOpen) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setMobileOpen(false); }; document.addEventListener("keydown", close); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", close); document.body.style.overflow = ""; }; }, [mobileOpen]);
  const showNewSaleShortcut = location.pathname !== "/sales" && user && routeAllowed("/sales", user.role);
  return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-30 hidden w-[272px] lg:block"><SidebarContent /></aside>{mobileOpen ? <div className="fixed inset-0 z-40 lg:hidden"><button type="button" className="absolute inset-0 bg-slate-950/45" onClick={() => setMobileOpen(false)} aria-label="Close navigation" /><aside className="relative h-full w-[min(88vw,320px)] shadow-2xl"><SidebarContent onNavigate={() => setMobileOpen(false)} /><button type="button" className="absolute right-2 top-1 grid h-11 w-11 place-items-center text-white" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X size={22} /></button></aside></div> : null}<div className="lg:pl-[272px]"><header className="sticky top-0 z-20 flex min-h-16 flex-wrap items-center justify-between gap-3 border-b border-border bg-white px-4 py-2"><div className="flex min-w-0 items-center gap-3"><button type="button" className="focus-ring flex min-h-11 items-center gap-2 rounded-lg border px-3 lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu size={22} /> Menu</button><div className="truncate font-semibold">{user?.full_name}</div></div><button type="button" onClick={() => { logout(); navigate("/login", { replace: true }); }} className="focus-ring flex min-h-11 shrink-0 items-center gap-2 rounded-lg px-3 font-semibold text-slate-700"><LogOut size={18} /> Sign out</button>{showNewSaleShortcut ? <div className="flex w-full justify-end border-t border-border pt-2"><button type="button" aria-label="Start new sale" onClick={() => navigate("/sales")} className="focus-ring flex h-12 items-center gap-2 rounded-full bg-primary-700 px-5 font-bold text-white shadow-lg" data-testid="new-sale-shortcut"><ShoppingCart size={22} aria-hidden="true" /> New Sale</button></div> : null}</header><ConnectionStatus /><main className="min-w-0 px-4 py-5 pb-24 md:px-6 lg:px-8"><div key={`${user?.id}:${location.pathname}`} className="page-enter"><Outlet /></div></main></div></div>;
}
