import { useEffect, useState } from "react";
import { Boxes, ClipboardPenLine, FolderTree, LayoutDashboard, LogOut, Menu, Package, PackagePlus, ReceiptText, ShoppingCart, X } from "lucide-react";
import { NavLink, Outlet, useLocation } from "react-router-dom";
import { useAuth } from "../hooks/useAuth";

const navigation = [
  { label: "Overview", items: [{ to: "/", label: "Dashboard", icon: LayoutDashboard, end: true }] },
  { label: "Sales", items: [{ to: "/sales", label: "New Sale", icon: ShoppingCart, end: true }, { to: "/sales/history", label: "Sales History", icon: ReceiptText }] },
  { label: "Inventory", items: [{ to: "/products", label: "Products", icon: Package }, { to: "/categories", label: "Categories & Brands", icon: FolderTree }, { to: "/purchases", label: "Purchases", icon: PackagePlus }, { to: "/stock", label: "Stock", icon: Boxes, end: true }, { to: "/stock/adjustment", label: "Stock Adjustment", icon: ClipboardPenLine }] },
];

function SidebarContent({ compact = false, onNavigate }: { compact?: boolean; onNavigate?: () => void }) {
  const { user, logout } = useAuth();
  return <div className="flex h-full flex-col bg-primary-700 text-white"><div className={`flex h-24 items-center border-b border-white/10 ${compact ? "justify-center px-2" : "px-5"}`}><div className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-surface text-lg font-bold text-primary-800 shadow-sm">R</div>{!compact ? <div className="ml-3 min-w-0"><div className="truncate text-2xl font-bold">Rainbow</div><div className="text-xs font-medium text-primary-100">Retail ERP</div></div> : null}</div><nav className={`flex-1 overflow-y-auto py-4 ${compact ? "space-y-2 px-3" : "space-y-5 px-4"}`} aria-label="Main navigation">{navigation.map((group) => <div key={group.label}>{!compact ? <div className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-primary-200">{group.label}</div> : null}<div className="space-y-1.5">{group.items.map((item) => { const Icon = item.icon; return <NavLink key={item.to} to={item.to} end={item.end} onClick={onNavigate} title={compact ? item.label : undefined} className={({ isActive }) => `group relative flex h-12 items-center rounded-xl font-medium transition-all duration-200 ${compact ? "justify-center px-2" : "gap-3 px-4 text-[15px]"} ${isActive ? "bg-gradient-to-r from-white/20 to-white/10 font-bold text-white shadow-sm" : "text-primary-50/85 hover:bg-white/10 hover:text-white"}`}>{({ isActive }) => <>{isActive ? <span className="absolute inset-y-2.5 left-0 w-1 rounded-r-full bg-amber-300" /> : null}<Icon size={isActive ? 23 : 21} strokeWidth={isActive ? 2.3 : 2} className="shrink-0 transition-all duration-200 group-hover:scale-105 group-hover:text-amber-200" />{!compact ? <span className="truncate">{item.label}</span> : null}</>}</NavLink>; })}</div></div>)}</nav><div className={`border-t border-white/10 p-4 ${compact ? "flex justify-center" : ""}`}>{!compact ? <div className="mb-3 flex items-center gap-3 rounded-lg bg-black/10 p-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/15 text-sm font-bold">{user?.full_name?.charAt(0) || "U"}</div><div className="min-w-0"><div className="truncate text-sm font-semibold">{user?.full_name}</div><div className="truncate text-xs text-primary-100">{user?.role}</div></div></div> : null}<button type="button" onClick={logout} title="Logout" aria-label="Logout" className={`focus-ring flex h-11 items-center rounded-lg text-sm font-medium text-primary-50 transition duration-200 hover:bg-white/10 hover:text-white ${compact ? "w-11 justify-center" : "w-full gap-3 px-3"}`}><LogOut size={20} />{!compact ? <span>Logout</span> : null}</button></div></div>;
}

export default function AppLayout() {
  const { user } = useAuth(); const location = useLocation(); const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { if (!mobileOpen) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setMobileOpen(false); }; document.addEventListener("keydown", onKeyDown); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", onKeyDown); document.body.style.overflow = ""; }; }, [mobileOpen]);
  return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-30 hidden w-[272px] shadow-xl shadow-slate-900/10 lg:block"><SidebarContent /></aside><aside className="fixed inset-y-0 left-0 z-30 hidden w-[88px] shadow-lg md:block lg:hidden"><SidebarContent compact /></aside>{mobileOpen ? <div className="fixed inset-0 z-40 md:hidden"><button type="button" className="absolute inset-0 bg-slate-950/45 backdrop-blur-sm" onClick={() => setMobileOpen(false)} aria-label="Close navigation" /><aside className="relative h-full w-[min(86vw,288px)] shadow-2xl"><SidebarContent onNavigate={() => setMobileOpen(false)} /><button type="button" className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-lg text-primary-50 hover:bg-white/10" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X size={22} /></button></aside></div> : null}<div className="md:pl-[88px] lg:pl-[272px]"><header className="sticky top-0 z-20 h-16 border-b border-border/80 bg-surface/90 px-4 backdrop-blur-xl md:px-6 lg:px-8"><div className="flex h-full items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><button type="button" className="focus-ring grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-border bg-surface text-slate-700 shadow-sm md:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu size={22} /></button><div className="min-w-0"><div className="truncate text-sm font-semibold text-foreground md:hidden">Rainbow Fashions</div><div className="hidden text-sm font-semibold text-foreground md:block">{user?.full_name}</div><div className="truncate text-xs text-muted">{user?.email}</div></div></div><div className="hidden items-center gap-2 rounded-full border border-border bg-surface-subtle py-1.5 pl-2 pr-3 text-sm font-medium text-slate-700 sm:flex"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary-100 font-bold text-primary-800">{user?.full_name?.charAt(0) || "U"}</span>{user?.role}</div></div></header><main className="min-w-0 px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div key={location.pathname} className="page-enter"><Outlet /></div></main></div></div>;
}
