import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "../api/client";
import PageHeader from "../components/PageHeader";
import ErrorState from "../components/ErrorState";
import { Button } from "../components/ui/button";
import { useDebouncedValue } from "../hooks/useDebouncedValue";

type Audit = { id: string; created_at: string; action: string; actor: string; reference?: string; reason?: string; before_data?: Record<string, unknown>; after_data?: Record<string, unknown>; request_id?: string };
export default function AuditLogPage() {
  const [search, setSearch] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [skip, setSkip] = useState(0);
  const term = useDebouncedValue(search, 300);
  const params = new URLSearchParams({ skip: String(skip), limit: "50" }); if (term) params.set("search", term); if (start) params.set("start_date", start); if (end) params.set("end_date", end);
  const query = useQuery({ queryKey: ["audit-log", skip, term, start, end], queryFn: () => api.get<{ items: Audit[]; has_more: boolean }>(`/audit-log?${params}`) });
  return <div className="space-y-5"><PageHeader title="Audit Log" subtitle="Who changed what, and when. History is read only." /><section className="ds-surface grid gap-4 p-5 sm:grid-cols-3"><label className="field-label">Search action, person or bill<input className="field-input" value={search} onChange={(e) => { setSearch(e.target.value); setSkip(0); }} /></label><label className="field-label">From<input className="field-input" type="date" value={start} onChange={(e) => { setStart(e.target.value); setSkip(0); }} /></label><label className="field-label">To<input className="field-input" type="date" min={start} value={end} onChange={(e) => { setEnd(e.target.value); setSkip(0); }} /></label></section>{query.error ? <ErrorState message={query.error.message} /> : query.isLoading ? <p role="status">Loading history…</p> : <section className="ds-surface divide-y divide-border px-5">{!query.data?.items.length && <p className="py-8">No matching actions found.</p>}{query.data?.items.map((event) => <article key={event.id} className="py-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-bold">{event.action.replace(/_/g, " ")}</h2><time dateTime={event.created_at}>{new Date(event.created_at).toLocaleString("en-IN")}</time></div><p className="mt-1">{event.actor}{event.reference && !/^[a-f0-9-]{36}$/i.test(event.reference) ? ` · ${event.reference}` : ""}</p>{event.reason && <p className="mt-2">Reason: {event.reason}</p>}<details className="mt-2"><summary className="cursor-pointer py-2 font-medium">Details</summary><div className="grid gap-4 sm:grid-cols-2">{[["Before", event.before_data], ["After", event.after_data]].map(([label, value]) => value ? <div key={String(label)}><h3 className="font-semibold">{String(label)}</h3><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-100 p-3 text-sm">{JSON.stringify(value, null, 2)}</pre></div> : null)}</div>{event.request_id && <p className="mt-3 break-all text-sm">Support reference: {event.request_id}</p>}</details></article>)}</section>}<div className="flex justify-end gap-3"><Button variant="secondary" disabled={!skip} onClick={() => setSkip(Math.max(0, skip - 50))}>Newer</Button><Button variant="secondary" disabled={!query.data?.has_more} onClick={() => setSkip(skip + 50)}>Older</Button></div></div>;
}
