import { useEffect, useState } from "react";
import { api } from "../api/client";
import { useAuth } from "../hooks/useAuth";
import PageHeader from "../components/PageHeader";
import ErrorState from "../components/ErrorState";
import { Button } from "../components/ui/button";
import { money } from "../utils/format";

type ImportError = { message: string };
type ImportRow = { row_number: number; normalized_data: Record<string, string>; errors: ImportError[] };
type OpeningImport = { id: string; status: string; original_filename: string; row_count: number; valid_row_count: number; error_count: number; total_quantity: number; total_cost_value: string; total_retail_value: string; validation_summary: Record<string, unknown>; rows?: ImportRow[]; errors?: ImportError[] };
export default function OpeningStockImportPage() {
  const { user } = useAuth(); const [imports, setImports] = useState<OpeningImport[]>([]); const [selected, setSelected] = useState<OpeningImport | null>(null);
  const [file, setFile] = useState<File | null>(null); const [shared, setShared] = useState(false); const [confirmation, setConfirmation] = useState(""); const [reason, setReason] = useState(""); const [page, setPage] = useState(1); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [integrity, setIntegrity] = useState<number | null>(null);
  const ready = selected?.status === "READY_TO_CONFIRM" && selected.error_count === 0;
  async function refresh() { setImports(await api.get<OpeningImport[]>("/opening-stock-imports")); }
  useEffect(() => { if (user?.role === "OWNER") void refresh().catch((cause) => setError(cause.message)); }, [user?.role]);
  async function inspect(id: string, nextPage = 1) { const result = await api.get<OpeningImport>(`/opening-stock-imports/${id}?page=${nextPage}`); setSelected(result); setPage(nextPage); setConfirmation(""); setIntegrity(null); if (result.status === "COMPLETED") { const check = await api.get<{critical_mismatches:number}>("/inventory/reconciliation/summary"); setIntegrity(check.critical_mismatches); } }
  async function act(work: () => Promise<void>) { setBusy(true); setError(""); try { await work(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not complete this step. Try again."); } finally { setBusy(false); } }
  async function upload() { if (!file) return; const form = new FormData(); form.append("file", file); form.append("confirm_shared_barcodes", String(shared)); const created = await api.post<OpeningImport>("/opening-stock-imports/upload", form); await refresh(); await inspect(created.id); }
  async function post() { if (!selected) return; await api.post(`/opening-stock-imports/${selected.id}/confirm`, { confirmation, idempotency_key: `opening-${selected.id}` }); await refresh(); await inspect(selected.id); }
  async function download(path: string, filename: string) { const url = URL.createObjectURL(await api.getBlob(path)); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
  async function recheck() { if (!selected) return; await api.post(`/opening-stock-imports/${selected.id}/revalidate`, {}); await inspect(selected.id); await refresh(); }
  async function reverse() { if (!selected) return; await api.post(`/opening-stock-imports/${selected.id}/reverse`, { confirmation, reason }); await inspect(selected.id); await refresh(); }
  if (user?.role !== "OWNER") return <ErrorState message="Only the owner can set up opening stock." />;
  return <><PageHeader title="Opening Stock Import" subtitle="Upload your file, check every size and total, then confirm once." /><div className="mx-auto max-w-6xl space-y-5"><ol aria-label="Opening stock steps" className="grid gap-2 sm:grid-cols-3">{["Upload File", "Check Data", "Fix Problems", "Review Totals", "Confirm Stock", "Completed"].map((step,index) => <li key={step} className="rounded-lg border bg-white p-3 font-semibold">{index+1}. {step}</li>)}</ol>{error && <ErrorState message={error} />}<section className="ds-surface space-y-4 p-5"><h2 className="text-lg font-bold">1. Upload opening stock</h2><p>Up to 20,000 rows. Each size needs its own row and SKU. Replace the sample row with your real opening stock.</p><Button variant="secondary" disabled={busy} onClick={() => void act(() => download("/opening-stock-imports/template", "opening-stock-template.csv"))}>Download sample CSV</Button><label className="field-label">Choose CSV or Excel file<input type="file" accept=".csv,.xlsx" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-5 w-5" checked={shared} onChange={(event) => setShared(event.target.checked)} /><span>This file intentionally shares supplier barcodes across sizes. I have checked each size and SKU.</span></label><p className="rounded-lg bg-blue-50 p-3">Uploading does not change your stock. You can review and correct errors first.</p><Button disabled={!file || busy} onClick={() => void act(upload)}>{busy ? "Checking…" : "Upload and check"}</Button></section>
    {selected && <section className="ds-surface space-y-4 p-5"><h2 className="text-lg font-bold">2. Review {selected.original_filename}</h2><p>{selected.status.replace(/_/g, " ")} · {selected.valid_row_count} valid rows of {selected.row_count} · {selected.error_count} errors</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Rows", String(selected.row_count)], ["New products", String(selected.validation_summary.new_products ?? "Check preview again")], ["Existing products", String(selected.validation_summary.existing_products ?? "Check preview again")], ["Errors", String(selected.error_count)], ["Total pieces", selected.total_quantity.toLocaleString()], ["Cost value", money(selected.total_cost_value)], ["Selling value", money(selected.total_retail_value)], ["MRP value", money(String(selected.validation_summary.total_mrp_value ?? 0))]].map(([title, value]) => <div key={title} className="rounded border p-3"><span className="text-sm">{title}</span><strong className="block text-lg">{value}</strong></div>)}</div>{Array.isArray(selected.validation_summary.warnings) && <p>Warnings: {selected.validation_summary.warnings.length ? selected.validation_summary.warnings.join(" ") : "None"}</p>}{selected.errors?.map((item, index) => <ErrorState key={index} message={item.message} />)}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Row", "Product", "Size / colour", "SKU", "Barcode", "Qty", "Check"].map((name) => <th className="p-2" key={name}>{name}</th>)}</tr></thead><tbody>{selected.rows?.map((row) => <tr key={row.row_number} className="border-t"><td className="p-2">{row.row_number}</td><td className="p-2">{row.normalized_data.product_name}</td><td className="p-2">{row.normalized_data.size || "Standard"} {row.normalized_data.color || row.normalized_data.colour}</td><td className="p-2">{row.normalized_data.sku}</td><td className="p-2">{row.normalized_data.barcode}</td><td className="p-2">{row.normalized_data.quantity}</td><td className="p-2">{row.errors.length ? row.errors.map((item) => item.message).join(" ") : "Ready"}</td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center gap-3"><Button variant="secondary" disabled={page <= 1 || busy} onClick={() => void act(() => inspect(selected.id, page - 1))}>Previous</Button><span>Page {page} / {Math.max(1, Math.ceil(selected.row_count / 200))}</span><Button variant="secondary" disabled={page * 200 >= selected.row_count || busy} onClick={() => void act(() => inspect(selected.id, page + 1))}>Next</Button>{selected.error_count > 0 && <Button variant="secondary" disabled={busy} onClick={() => void act(() => download(`/opening-stock-imports/${selected.id}/errors.csv`, "opening-stock-errors.csv"))}>Download errors</Button>}</div>
    {["READY_TO_CONFIRM", "REVIEW_REQUIRED"].includes(selected.status) && <><p>Fix file errors and upload the corrected file. After fixing backup or product details, check this preview again.</p><Button variant="secondary" disabled={busy} onClick={() => void act(recheck)}>Check preview again</Button></>}{ready && <div className="space-y-3 rounded-lg border border-amber-200 bg-amber-50 p-4"><h3 className="text-lg font-bold">5. Confirm opening stock</h3><p>Check every size and total above. Database, uploads and offsite backups plus a restore check must pass again when you confirm. All rows are saved together.</p><label className="field-label">Type POST OPENING STOCK<input className="field-input" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><Button disabled={busy || confirmation !== "POST OPENING STOCK"} onClick={() => void act(post)}>Post opening stock</Button></div>}{selected.status === "COMPLETED" && <div role="status" className="rounded-lg bg-emerald-50 p-4"><h3 className="text-lg font-bold">6. Completed</h3><p>{selected.total_quantity} pieces posted. Stock discrepancies: {integrity === null ? "Check pending" : integrity}. Open Inventory Integrity and physically count the pilot before the next import.</p></div>}{selected.status === "COMPLETED" && <details className="rounded border p-4"><summary className="cursor-pointer font-semibold">Reverse this opening stock</summary><p className="my-3">Only available before later activity on these sizes. The original entry stays in history.</p><label className="field-label">Reason<input className="field-input" value={reason} onChange={(event) => setReason(event.target.value)} /></label><label className="field-label mt-3">Type REVERSE OPENING STOCK<input className="field-input" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><Button className="mt-3" disabled={busy || confirmation !== "REVERSE OPENING STOCK" || reason.trim().length < 8} onClick={() => void act(reverse)}>Reverse opening stock</Button></details>}</section>}
    <section className="ds-surface p-5"><h2 className="mb-3 text-lg font-bold">Recent imports</h2>{imports.map((item) => <button disabled={busy} key={item.id} className="flex min-h-14 w-full items-center justify-between gap-3 border-t py-3 text-left" onClick={() => void act(() => inspect(item.id))}><strong>{item.original_filename}</strong><span>{item.status.replace(/_/g, " ")} · {item.row_count} rows</span></button>)}{!imports.length && <p>No opening stock files uploaded yet.</p>}</section></div></>;
}
